package io.smartnexus.ats.thrift;

import java.util.ArrayList;
import java.util.BitSet;
import java.util.Collections;
import java.util.EnumMap;
import java.util.EnumSet;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.annotation.Generated;
import org.apache.thrift.protocol.TTupleProtocol;
/**
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;
import org.apache.thrift.scheme.TupleScheme;

@SuppressWarnings({ "cast", "rawtypes", "serial", "unchecked" })
/**
 * Data structure associated with received messages
 */
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2018-08-30")
public class RcvMsgStruct implements org.apache.thrift.TBase<RcvMsgStruct, RcvMsgStruct._Fields>, java.io.Serializable,
		Cloneable, Comparable<RcvMsgStruct> {
	private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct(
			"RcvMsgStruct");

	private static final org.apache.thrift.protocol.TField MESSAGE_FIELD_DESC = new org.apache.thrift.protocol.TField(
			"Message", org.apache.thrift.protocol.TType.STRING, (short) 1);
	private static final org.apache.thrift.protocol.TField COOKIE_FIELD_DESC = new org.apache.thrift.protocol.TField(
			"Cookie", org.apache.thrift.protocol.TType.STRING, (short) 2);

	private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
	static {
		schemes.put(StandardScheme.class, new RcvMsgStructStandardSchemeFactory());
		schemes.put(TupleScheme.class, new RcvMsgStructTupleSchemeFactory());
	}

	/**
	 * Message in JSON format
	 */
	public String Message; // required
	/**
	 * Message identifier/token/sequence number
	 */
	public String Cookie; // required

	/**
	 * The set of fields this struct contains, along with convenience methods
	 * for finding and manipulating them.
	 */
	public enum _Fields implements org.apache.thrift.TFieldIdEnum {
		/**
		 * Message in JSON format
		 */
		MESSAGE((short) 1, "Message"),
		/**
		 * Message identifier/token/sequence number
		 */
		COOKIE((short) 2, "Cookie");

		private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

		static {
			for (_Fields field : EnumSet.allOf(_Fields.class)) {
				byName.put(field.getFieldName(), field);
			}
		}

		/**
		 * Find the _Fields constant that matches fieldId, or null if its not
		 * found.
		 */
		public static _Fields findByThriftId(int fieldId) {
			switch (fieldId) {
			case 1: // MESSAGE
				return MESSAGE;
			case 2: // COOKIE
				return COOKIE;
			default:
				return null;
			}
		}

		/**
		 * Find the _Fields constant that matches fieldId, throwing an exception
		 * if it is not found.
		 */
		public static _Fields findByThriftIdOrThrow(int fieldId) {
			_Fields fields = findByThriftId(fieldId);
			if (fields == null)
				throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
			return fields;
		}

		/**
		 * Find the _Fields constant that matches name, or null if its not
		 * found.
		 */
		public static _Fields findByName(String name) {
			return byName.get(name);
		}

		private final short _thriftId;
		private final String _fieldName;

		_Fields(short thriftId, String fieldName) {
			_thriftId = thriftId;
			_fieldName = fieldName;
		}

		public short getThriftFieldId() {
			return _thriftId;
		}

		public String getFieldName() {
			return _fieldName;
		}
	}

	// isset id assignments
	public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
	static {
		Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(
				_Fields.class);
		tmpMap.put(_Fields.MESSAGE,
				new org.apache.thrift.meta_data.FieldMetaData("Message",
						org.apache.thrift.TFieldRequirementType.DEFAULT,
						new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
		tmpMap.put(_Fields.COOKIE,
				new org.apache.thrift.meta_data.FieldMetaData("Cookie", org.apache.thrift.TFieldRequirementType.DEFAULT,
						new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
		metaDataMap = Collections.unmodifiableMap(tmpMap);
		org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(RcvMsgStruct.class, metaDataMap);
	}

	public RcvMsgStruct() {
	}

	public RcvMsgStruct(String Message, String Cookie) {
		this();
		this.Message = Message;
		this.Cookie = Cookie;
	}

	/**
	 * Performs a deep copy on <i>other</i>.
	 */
	public RcvMsgStruct(RcvMsgStruct other) {
		if (other.isSetMessage()) {
			this.Message = other.Message;
		}
		if (other.isSetCookie()) {
			this.Cookie = other.Cookie;
		}
	}

	public RcvMsgStruct deepCopy() {
		return new RcvMsgStruct(this);
	}

	@Override
	public void clear() {
		this.Message = null;
		this.Cookie = null;
	}

	/**
	 * Message in JSON format
	 */
	public String getMessage() {
		return this.Message;
	}

	/**
	 * Message in JSON format
	 */
	public RcvMsgStruct setMessage(String Message) {
		this.Message = Message;
		return this;
	}

	public void unsetMessage() {
		this.Message = null;
	}

	/**
	 * Returns true if field Message is set (has been assigned a value) and
	 * false otherwise
	 */
	public boolean isSetMessage() {
		return this.Message != null;
	}

	public void setMessageIsSet(boolean value) {
		if (!value) {
			this.Message = null;
		}
	}

	/**
	 * Message identifier/token/sequence number
	 */
	public String getCookie() {
		return this.Cookie;
	}

	/**
	 * Message identifier/token/sequence number
	 */
	public RcvMsgStruct setCookie(String Cookie) {
		this.Cookie = Cookie;
		return this;
	}

	public void unsetCookie() {
		this.Cookie = null;
	}

	/**
	 * Returns true if field Cookie is set (has been assigned a value) and false
	 * otherwise
	 */
	public boolean isSetCookie() {
		return this.Cookie != null;
	}

	public void setCookieIsSet(boolean value) {
		if (!value) {
			this.Cookie = null;
		}
	}

	public void setFieldValue(_Fields field, Object value) {
		switch (field) {
		case MESSAGE:
			if (value == null) {
				unsetMessage();
			} else {
				setMessage((String) value);
			}
			break;

		case COOKIE:
			if (value == null) {
				unsetCookie();
			} else {
				setCookie((String) value);
			}
			break;

		}
	}

	public Object getFieldValue(_Fields field) {
		switch (field) {
		case MESSAGE:
			return getMessage();

		case COOKIE:
			return getCookie();

		}
		throw new IllegalStateException();
	}

	/**
	 * Returns true if field corresponding to fieldID is set (has been assigned
	 * a value) and false otherwise
	 */
	public boolean isSet(_Fields field) {
		if (field == null) {
			throw new IllegalArgumentException();
		}

		switch (field) {
		case MESSAGE:
			return isSetMessage();
		case COOKIE:
			return isSetCookie();
		}
		throw new IllegalStateException();
	}

	@Override
	public boolean equals(Object that) {
		if (that == null)
			return false;
		if (that instanceof RcvMsgStruct)
			return this.equals((RcvMsgStruct) that);
		return false;
	}

	public boolean equals(RcvMsgStruct that) {
		if (that == null)
			return false;

		boolean this_present_Message = true && this.isSetMessage();
		boolean that_present_Message = true && that.isSetMessage();
		if (this_present_Message || that_present_Message) {
			if (!(this_present_Message && that_present_Message))
				return false;
			if (!this.Message.equals(that.Message))
				return false;
		}

		boolean this_present_Cookie = true && this.isSetCookie();
		boolean that_present_Cookie = true && that.isSetCookie();
		if (this_present_Cookie || that_present_Cookie) {
			if (!(this_present_Cookie && that_present_Cookie))
				return false;
			if (!this.Cookie.equals(that.Cookie))
				return false;
		}

		return true;
	}

	@Override
	public int hashCode() {
		List<Object> list = new ArrayList<Object>();

		boolean present_Message = true && (isSetMessage());
		list.add(present_Message);
		if (present_Message)
			list.add(Message);

		boolean present_Cookie = true && (isSetCookie());
		list.add(present_Cookie);
		if (present_Cookie)
			list.add(Cookie);

		return list.hashCode();
	}

	@Override
	public int compareTo(RcvMsgStruct other) {
		if (!getClass().equals(other.getClass())) {
			return getClass().getName().compareTo(other.getClass().getName());
		}

		int lastComparison = 0;

		lastComparison = Boolean.valueOf(isSetMessage()).compareTo(other.isSetMessage());
		if (lastComparison != 0) {
			return lastComparison;
		}
		if (isSetMessage()) {
			lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.Message, other.Message);
			if (lastComparison != 0) {
				return lastComparison;
			}
		}
		lastComparison = Boolean.valueOf(isSetCookie()).compareTo(other.isSetCookie());
		if (lastComparison != 0) {
			return lastComparison;
		}
		if (isSetCookie()) {
			lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.Cookie, other.Cookie);
			if (lastComparison != 0) {
				return lastComparison;
			}
		}
		return 0;
	}

	public _Fields fieldForId(int fieldId) {
		return _Fields.findByThriftId(fieldId);
	}

	public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
		schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
	}

	public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
		schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("RcvMsgStruct(");
		boolean first = true;

		sb.append("Message:");
		if (this.Message == null) {
			sb.append("null");
		} else {
			sb.append(this.Message);
		}
		first = false;
		if (!first)
			sb.append(", ");
		sb.append("Cookie:");
		if (this.Cookie == null) {
			sb.append("null");
		} else {
			sb.append(this.Cookie);
		}
		first = false;
		sb.append(")");
		return sb.toString();
	}

	public void validate() throws org.apache.thrift.TException {
		// check for required fields
		// check for sub-struct validity
	}

	private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
		try {
			write(new org.apache.thrift.protocol.TCompactProtocol(
					new org.apache.thrift.transport.TIOStreamTransport(out)));
		} catch (org.apache.thrift.TException te) {
			throw new java.io.IOException(te);
		}
	}

	private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
		try {
			read(new org.apache.thrift.protocol.TCompactProtocol(
					new org.apache.thrift.transport.TIOStreamTransport(in)));
		} catch (org.apache.thrift.TException te) {
			throw new java.io.IOException(te);
		}
	}

	private static class RcvMsgStructStandardSchemeFactory implements SchemeFactory {
		public RcvMsgStructStandardScheme getScheme() {
			return new RcvMsgStructStandardScheme();
		}
	}

	private static class RcvMsgStructStandardScheme extends StandardScheme<RcvMsgStruct> {

		public void read(org.apache.thrift.protocol.TProtocol iprot, RcvMsgStruct struct)
				throws org.apache.thrift.TException {
			org.apache.thrift.protocol.TField schemeField;
			iprot.readStructBegin();
			while (true) {
				schemeField = iprot.readFieldBegin();
				if (schemeField.type == org.apache.thrift.protocol.TType.STOP) {
					break;
				}
				switch (schemeField.id) {
				case 1: // MESSAGE
					if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
						struct.Message = iprot.readString();
						struct.setMessageIsSet(true);
					} else {
						org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
					}
					break;
				case 2: // COOKIE
					if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
						struct.Cookie = iprot.readString();
						struct.setCookieIsSet(true);
					} else {
						org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
					}
					break;
				default:
					org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
				}
				iprot.readFieldEnd();
			}
			iprot.readStructEnd();

			// check for required fields of primitive type, which can't be
			// checked in the validate method
			struct.validate();
		}

		public void write(org.apache.thrift.protocol.TProtocol oprot, RcvMsgStruct struct)
				throws org.apache.thrift.TException {
			struct.validate();

			oprot.writeStructBegin(STRUCT_DESC);
			if (struct.Message != null) {
				oprot.writeFieldBegin(MESSAGE_FIELD_DESC);
				oprot.writeString(struct.Message);
				oprot.writeFieldEnd();
			}
			if (struct.Cookie != null) {
				oprot.writeFieldBegin(COOKIE_FIELD_DESC);
				oprot.writeString(struct.Cookie);
				oprot.writeFieldEnd();
			}
			oprot.writeFieldStop();
			oprot.writeStructEnd();
		}

	}

	private static class RcvMsgStructTupleSchemeFactory implements SchemeFactory {
		public RcvMsgStructTupleScheme getScheme() {
			return new RcvMsgStructTupleScheme();
		}
	}

	private static class RcvMsgStructTupleScheme extends TupleScheme<RcvMsgStruct> {

		@Override
		public void write(org.apache.thrift.protocol.TProtocol prot, RcvMsgStruct struct)
				throws org.apache.thrift.TException {
			TTupleProtocol oprot = (TTupleProtocol) prot;
			BitSet optionals = new BitSet();
			if (struct.isSetMessage()) {
				optionals.set(0);
			}
			if (struct.isSetCookie()) {
				optionals.set(1);
			}
			oprot.writeBitSet(optionals, 2);
			if (struct.isSetMessage()) {
				oprot.writeString(struct.Message);
			}
			if (struct.isSetCookie()) {
				oprot.writeString(struct.Cookie);
			}
		}

		@Override
		public void read(org.apache.thrift.protocol.TProtocol prot, RcvMsgStruct struct)
				throws org.apache.thrift.TException {
			TTupleProtocol iprot = (TTupleProtocol) prot;
			BitSet incoming = iprot.readBitSet(2);
			if (incoming.get(0)) {
				struct.Message = iprot.readString();
				struct.setMessageIsSet(true);
			}
			if (incoming.get(1)) {
				struct.Cookie = iprot.readString();
				struct.setCookieIsSet(true);
			}
		}
	}

}
