package io.smartnexus.ats.thrift;

import java.util.ArrayList;
import java.util.BitSet;
import java.util.Collections;
import java.util.EnumMap;
import java.util.EnumSet;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.annotation.Generated;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;
import org.apache.thrift.scheme.TupleScheme;
/**
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
@SuppressWarnings({ "cast", "rawtypes", "serial", "unchecked" })
/**
 * Data structure associated with Agent events
 */
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2018-08-30")
public class EventDataStruct implements org.apache.thrift.TBase<EventDataStruct, EventDataStruct._Fields>,
		java.io.Serializable, Cloneable, Comparable<EventDataStruct> {
	private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct(
			"EventDataStruct");

	private static final org.apache.thrift.protocol.TField TYPE_FIELD_DESC = new org.apache.thrift.protocol.TField(
			"Type", org.apache.thrift.protocol.TType.I32, (short) 1);
	private static final org.apache.thrift.protocol.TField OTA_URL_FIELD_DESC = new org.apache.thrift.protocol.TField(
			"OtaURL", org.apache.thrift.protocol.TType.STRING, (short) 2);
	private static final org.apache.thrift.protocol.TField TIMESTAMP_FIELD_DESC = new org.apache.thrift.protocol.TField(
			"Timestamp", org.apache.thrift.protocol.TType.STRING, (short) 3);

	private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
	static {
		schemes.put(StandardScheme.class, new EventDataStructStandardSchemeFactory());
		schemes.put(TupleScheme.class, new EventDataStructTupleSchemeFactory());
	}

	/**
	 * The type of event
	 * 
	 * @see EventType
	 */
	public EventType Type; // required
	/**
	 * URL for new OTA image--valid when Type == EVENT_NEW_OTA_IMAGE_AVAIL
	 */
	public String OtaURL; // required
	/**
	 * Timestamp from server--valid when Type == EVENT_TIMESTAMP_AVAIL
	 */
	public String Timestamp; // required

	/**
	 * The set of fields this struct contains, along with convenience methods
	 * for finding and manipulating them.
	 */
	public enum _Fields implements org.apache.thrift.TFieldIdEnum {
		/**
		 * The type of event
		 * 
		 * @see EventType
		 */
		TYPE((short) 1, "Type"),
		/**
		 * URL for new OTA image--valid when Type == EVENT_NEW_OTA_IMAGE_AVAIL
		 */
		OTA_URL((short) 2, "OtaURL"),
		/**
		 * Timestamp from server--valid when Type == EVENT_TIMESTAMP_AVAIL
		 */
		TIMESTAMP((short) 3, "Timestamp");

		private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

		static {
			for (_Fields field : EnumSet.allOf(_Fields.class)) {
				byName.put(field.getFieldName(), field);
			}
		}

		/**
		 * Find the _Fields constant that matches fieldId, or null if its not
		 * found.
		 */
		public static _Fields findByThriftId(int fieldId) {
			switch (fieldId) {
			case 1: // TYPE
				return TYPE;
			case 2: // OTA_URL
				return OTA_URL;
			case 3: // TIMESTAMP
				return TIMESTAMP;
			default:
				return null;
			}
		}

		/**
		 * Find the _Fields constant that matches fieldId, throwing an exception
		 * if it is not found.
		 */
		public static _Fields findByThriftIdOrThrow(int fieldId) {
			_Fields fields = findByThriftId(fieldId);
			if (fields == null)
				throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
			return fields;
		}

		/**
		 * Find the _Fields constant that matches name, or null if its not
		 * found.
		 */
		public static _Fields findByName(String name) {
			return byName.get(name);
		}

		private final short _thriftId;
		private final String _fieldName;

		_Fields(short thriftId, String fieldName) {
			_thriftId = thriftId;
			_fieldName = fieldName;
		}

		public short getThriftFieldId() {
			return _thriftId;
		}

		public String getFieldName() {
			return _fieldName;
		}
	}

	// isset id assignments
	public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
	static {
		Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(
				_Fields.class);
		tmpMap.put(_Fields.TYPE, new org.apache.thrift.meta_data.FieldMetaData("Type",
				org.apache.thrift.TFieldRequirementType.DEFAULT,
				new org.apache.thrift.meta_data.EnumMetaData(org.apache.thrift.protocol.TType.ENUM, EventType.class)));
		tmpMap.put(_Fields.OTA_URL,
				new org.apache.thrift.meta_data.FieldMetaData("OtaURL", org.apache.thrift.TFieldRequirementType.DEFAULT,
						new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
		tmpMap.put(_Fields.TIMESTAMP,
				new org.apache.thrift.meta_data.FieldMetaData("Timestamp",
						org.apache.thrift.TFieldRequirementType.DEFAULT,
						new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
		metaDataMap = Collections.unmodifiableMap(tmpMap);
		org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(EventDataStruct.class, metaDataMap);
	}

	public EventDataStruct() {
	}

	public EventDataStruct(EventType Type, String OtaURL, String Timestamp) {
		this();
		this.Type = Type;
		this.OtaURL = OtaURL;
		this.Timestamp = Timestamp;
	}

	/**
	 * Performs a deep copy on <i>other</i>.
	 */
	public EventDataStruct(EventDataStruct other) {
		if (other.isSetType()) {
			this.Type = other.Type;
		}
		if (other.isSetOtaURL()) {
			this.OtaURL = other.OtaURL;
		}
		if (other.isSetTimestamp()) {
			this.Timestamp = other.Timestamp;
		}
	}

	public EventDataStruct deepCopy() {
		return new EventDataStruct(this);
	}

	@Override
	public void clear() {
		this.Type = null;
		this.OtaURL = null;
		this.Timestamp = null;
	}

	/**
	 * The type of event
	 * 
	 * @see EventType
	 */
	public EventType getType() {
		return this.Type;
	}

	/**
	 * The type of event
	 * 
	 * @see EventType
	 */
	public EventDataStruct setType(EventType Type) {
		this.Type = Type;
		return this;
	}

	public void unsetType() {
		this.Type = null;
	}

	/**
	 * Returns true if field Type is set (has been assigned a value) and false
	 * otherwise
	 */
	public boolean isSetType() {
		return this.Type != null;
	}

	public void setTypeIsSet(boolean value) {
		if (!value) {
			this.Type = null;
		}
	}

	/**
	 * URL for new OTA image--valid when Type == EVENT_NEW_OTA_IMAGE_AVAIL
	 */
	public String getOtaURL() {
		return this.OtaURL;
	}

	/**
	 * URL for new OTA image--valid when Type == EVENT_NEW_OTA_IMAGE_AVAIL
	 */
	public EventDataStruct setOtaURL(String OtaURL) {
		this.OtaURL = OtaURL;
		return this;
	}

	public void unsetOtaURL() {
		this.OtaURL = null;
	}

	/**
	 * Returns true if field OtaURL is set (has been assigned a value) and false
	 * otherwise
	 */
	public boolean isSetOtaURL() {
		return this.OtaURL != null;
	}

	public void setOtaURLIsSet(boolean value) {
		if (!value) {
			this.OtaURL = null;
		}
	}

	/**
	 * Timestamp from server--valid when Type == EVENT_TIMESTAMP_AVAIL
	 */
	public String getTimestamp() {
		return this.Timestamp;
	}

	/**
	 * Timestamp from server--valid when Type == EVENT_TIMESTAMP_AVAIL
	 */
	public EventDataStruct setTimestamp(String Timestamp) {
		this.Timestamp = Timestamp;
		return this;
	}

	public void unsetTimestamp() {
		this.Timestamp = null;
	}

	/**
	 * Returns true if field Timestamp is set (has been assigned a value) and
	 * false otherwise
	 */
	public boolean isSetTimestamp() {
		return this.Timestamp != null;
	}

	public void setTimestampIsSet(boolean value) {
		if (!value) {
			this.Timestamp = null;
		}
	}

	public void setFieldValue(_Fields field, Object value) {
		switch (field) {
		case TYPE:
			if (value == null) {
				unsetType();
			} else {
				setType((EventType) value);
			}
			break;

		case OTA_URL:
			if (value == null) {
				unsetOtaURL();
			} else {
				setOtaURL((String) value);
			}
			break;

		case TIMESTAMP:
			if (value == null) {
				unsetTimestamp();
			} else {
				setTimestamp((String) value);
			}
			break;

		}
	}

	public Object getFieldValue(_Fields field) {
		switch (field) {
		case TYPE:
			return getType();

		case OTA_URL:
			return getOtaURL();

		case TIMESTAMP:
			return getTimestamp();

		}
		throw new IllegalStateException();
	}

	/**
	 * Returns true if field corresponding to fieldID is set (has been assigned
	 * a value) and false otherwise
	 */
	public boolean isSet(_Fields field) {
		if (field == null) {
			throw new IllegalArgumentException();
		}

		switch (field) {
		case TYPE:
			return isSetType();
		case OTA_URL:
			return isSetOtaURL();
		case TIMESTAMP:
			return isSetTimestamp();
		}
		throw new IllegalStateException();
	}

	@Override
	public boolean equals(Object that) {
		if (that == null)
			return false;
		if (that instanceof EventDataStruct)
			return this.equals((EventDataStruct) that);
		return false;
	}

	public boolean equals(EventDataStruct that) {
		if (that == null)
			return false;

		boolean this_present_Type = true && this.isSetType();
		boolean that_present_Type = true && that.isSetType();
		if (this_present_Type || that_present_Type) {
			if (!(this_present_Type && that_present_Type))
				return false;
			if (!this.Type.equals(that.Type))
				return false;
		}

		boolean this_present_OtaURL = true && this.isSetOtaURL();
		boolean that_present_OtaURL = true && that.isSetOtaURL();
		if (this_present_OtaURL || that_present_OtaURL) {
			if (!(this_present_OtaURL && that_present_OtaURL))
				return false;
			if (!this.OtaURL.equals(that.OtaURL))
				return false;
		}

		boolean this_present_Timestamp = true && this.isSetTimestamp();
		boolean that_present_Timestamp = true && that.isSetTimestamp();
		if (this_present_Timestamp || that_present_Timestamp) {
			if (!(this_present_Timestamp && that_present_Timestamp))
				return false;
			if (!this.Timestamp.equals(that.Timestamp))
				return false;
		}

		return true;
	}

	@Override
	public int hashCode() {
		List<Object> list = new ArrayList<Object>();

		boolean present_Type = true && (isSetType());
		list.add(present_Type);
		if (present_Type)
			list.add(Type.getValue());

		boolean present_OtaURL = true && (isSetOtaURL());
		list.add(present_OtaURL);
		if (present_OtaURL)
			list.add(OtaURL);

		boolean present_Timestamp = true && (isSetTimestamp());
		list.add(present_Timestamp);
		if (present_Timestamp)
			list.add(Timestamp);

		return list.hashCode();
	}

	@Override
	public int compareTo(EventDataStruct other) {
		if (!getClass().equals(other.getClass())) {
			return getClass().getName().compareTo(other.getClass().getName());
		}

		int lastComparison = 0;

		lastComparison = Boolean.valueOf(isSetType()).compareTo(other.isSetType());
		if (lastComparison != 0) {
			return lastComparison;
		}
		if (isSetType()) {
			lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.Type, other.Type);
			if (lastComparison != 0) {
				return lastComparison;
			}
		}
		lastComparison = Boolean.valueOf(isSetOtaURL()).compareTo(other.isSetOtaURL());
		if (lastComparison != 0) {
			return lastComparison;
		}
		if (isSetOtaURL()) {
			lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.OtaURL, other.OtaURL);
			if (lastComparison != 0) {
				return lastComparison;
			}
		}
		lastComparison = Boolean.valueOf(isSetTimestamp()).compareTo(other.isSetTimestamp());
		if (lastComparison != 0) {
			return lastComparison;
		}
		if (isSetTimestamp()) {
			lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.Timestamp, other.Timestamp);
			if (lastComparison != 0) {
				return lastComparison;
			}
		}
		return 0;
	}

	public _Fields fieldForId(int fieldId) {
		return _Fields.findByThriftId(fieldId);
	}

	public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
		schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
	}

	public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
		schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("EventDataStruct(");
		boolean first = true;

		sb.append("Type:");
		if (this.Type == null) {
			sb.append("null");
		} else {
			sb.append(this.Type);
		}
		first = false;
		if (!first)
			sb.append(", ");
		sb.append("OtaURL:");
		if (this.OtaURL == null) {
			sb.append("null");
		} else {
			sb.append(this.OtaURL);
		}
		first = false;
		if (!first)
			sb.append(", ");
		sb.append("Timestamp:");
		if (this.Timestamp == null) {
			sb.append("null");
		} else {
			sb.append(this.Timestamp);
		}
		first = false;
		sb.append(")");
		return sb.toString();
	}

	public void validate() throws org.apache.thrift.TException {
		// check for required fields
		// check for sub-struct validity
	}

	private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
		try {
			write(new org.apache.thrift.protocol.TCompactProtocol(
					new org.apache.thrift.transport.TIOStreamTransport(out)));
		} catch (org.apache.thrift.TException te) {
			throw new java.io.IOException(te);
		}
	}

	private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
		try {
			read(new org.apache.thrift.protocol.TCompactProtocol(
					new org.apache.thrift.transport.TIOStreamTransport(in)));
		} catch (org.apache.thrift.TException te) {
			throw new java.io.IOException(te);
		}
	}

	private static class EventDataStructStandardSchemeFactory implements SchemeFactory {
		public EventDataStructStandardScheme getScheme() {
			return new EventDataStructStandardScheme();
		}
	}

	private static class EventDataStructStandardScheme extends StandardScheme<EventDataStruct> {

		public void read(org.apache.thrift.protocol.TProtocol iprot, EventDataStruct struct)
				throws org.apache.thrift.TException {
			org.apache.thrift.protocol.TField schemeField;
			iprot.readStructBegin();
			while (true) {
				schemeField = iprot.readFieldBegin();
				if (schemeField.type == org.apache.thrift.protocol.TType.STOP) {
					break;
				}
				switch (schemeField.id) {
				case 1: // TYPE
					if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
						struct.Type = EventType.findByValue(iprot.readI32());
						struct.setTypeIsSet(true);
					} else {
						org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
					}
					break;
				case 2: // OTA_URL
					if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
						struct.OtaURL = iprot.readString();
						struct.setOtaURLIsSet(true);
					} else {
						org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
					}
					break;
				case 3: // TIMESTAMP
					if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
						struct.Timestamp = iprot.readString();
						struct.setTimestampIsSet(true);
					} else {
						org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
					}
					break;
				default:
					org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
				}
				iprot.readFieldEnd();
			}
			iprot.readStructEnd();

			// check for required fields of primitive type, which can't be
			// checked in the validate method
			struct.validate();
		}

		public void write(org.apache.thrift.protocol.TProtocol oprot, EventDataStruct struct)
				throws org.apache.thrift.TException {
			struct.validate();

			oprot.writeStructBegin(STRUCT_DESC);
			if (struct.Type != null) {
				oprot.writeFieldBegin(TYPE_FIELD_DESC);
				oprot.writeI32(struct.Type.getValue());
				oprot.writeFieldEnd();
			}
			if (struct.OtaURL != null) {
				oprot.writeFieldBegin(OTA_URL_FIELD_DESC);
				oprot.writeString(struct.OtaURL);
				oprot.writeFieldEnd();
			}
			if (struct.Timestamp != null) {
				oprot.writeFieldBegin(TIMESTAMP_FIELD_DESC);
				oprot.writeString(struct.Timestamp);
				oprot.writeFieldEnd();
			}
			oprot.writeFieldStop();
			oprot.writeStructEnd();
		}

	}

	private static class EventDataStructTupleSchemeFactory implements SchemeFactory {
		public EventDataStructTupleScheme getScheme() {
			return new EventDataStructTupleScheme();
		}
	}

	private static class EventDataStructTupleScheme extends TupleScheme<EventDataStruct> {

		@Override
		public void write(org.apache.thrift.protocol.TProtocol prot, EventDataStruct struct)
				throws org.apache.thrift.TException {
			TTupleProtocol oprot = (TTupleProtocol) prot;
			BitSet optionals = new BitSet();
			if (struct.isSetType()) {
				optionals.set(0);
			}
			if (struct.isSetOtaURL()) {
				optionals.set(1);
			}
			if (struct.isSetTimestamp()) {
				optionals.set(2);
			}
			oprot.writeBitSet(optionals, 3);
			if (struct.isSetType()) {
				oprot.writeI32(struct.Type.getValue());
			}
			if (struct.isSetOtaURL()) {
				oprot.writeString(struct.OtaURL);
			}
			if (struct.isSetTimestamp()) {
				oprot.writeString(struct.Timestamp);
			}
		}

		@Override
		public void read(org.apache.thrift.protocol.TProtocol prot, EventDataStruct struct)
				throws org.apache.thrift.TException {
			TTupleProtocol iprot = (TTupleProtocol) prot;
			BitSet incoming = iprot.readBitSet(3);
			if (incoming.get(0)) {
				struct.Type = EventType.findByValue(iprot.readI32());
				struct.setTypeIsSet(true);
			}
			if (incoming.get(1)) {
				struct.OtaURL = iprot.readString();
				struct.setOtaURLIsSet(true);
			}
			if (incoming.get(2)) {
				struct.Timestamp = iprot.readString();
				struct.setTimestampIsSet(true);
			}
		}
	}

}
